theme = "github-dark"

speed = 22

background = true

loop = true

ignore_patterns = ["*.lock", "*.json", ".gitignore", "**/*.json", "**/*.lock", "**/*.test.*", "**/*.uid", "**/*.tscn", "**/*.png"]

order = "desc"
